"""
src/services/watermark.py
==========================
Domain service for watermark detection.

Rules:
- ZERO imports from torch, gradio, chatterbox
- Delegates raw detection to IWatermarkDetector (output port)
- Maps float score → WatermarkResult with human-readable verdict + message
- When detector is unavailable, returns 'unavailable' without calling detect()

Verdict thresholds (mirrors app.py logic):
    score >= 0.9  → "detected"
    score <= 0.1  → "not_detected"
    otherwise     → "inconclusive"
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from domain.models import WatermarkResult

if TYPE_CHECKING:
    from domain.types import WatermarkVerdict
    from ports.output import IWatermarkDetector


class WatermarkService:
    """Detects PerTh watermarks in generated audio clips.

    Args:
        detector: Infrastructure adapter that wraps the actual detection
                  library (e.g. ``resemble-perth``).  The adapter is
                  responsible for reporting availability; this service
                  never imports the detection library directly.
    """

    # Verdict thresholds — kept as class constants so they are easy to adjust
    # or override in tests without monkey-patching the entire service.
    _DETECTED_THRESHOLD: float = 0.9
    _NOT_DETECTED_THRESHOLD: float = 0.1

    def __init__(self, detector: IWatermarkDetector) -> None:
        self._detector = detector

    # ──────────────────────────────────────────────────────────────────────────
    # Public API
    # ──────────────────────────────────────────────────────────────────────────

    def detect(self, audio_path: str) -> WatermarkResult:
        """Detect whether *audio_path* carries a Chatterbox watermark.

        Returns:
            A :class:`~chatterbox_explorer.domain.models.WatermarkResult`
            whose ``verdict`` is one of:

            * ``"detected"``      — score ≥ 0.9
            * ``"not_detected"``  — score ≤ 0.1
            * ``"inconclusive"``  — 0.1 < score < 0.9
            * ``"unavailable"``   — detection library not installed / unusable

        Notes:
            ``detector.detect()`` is *not* called when the detector reports
            itself as unavailable.
        """
        if not self._detector.is_available():
            return WatermarkResult(
                score=0.0,
                verdict="unavailable",
                message=(
                    "Watermark detection is not available in this environment. "
                    "The detection library (resemble-perth) may not be installed "
                    "or may not include the full PerTh neural watermark detector."
                ),
                available=False,
            )

        score = float(self._detector.detect(audio_path))
        verdict, message = self._classify(score)

        return WatermarkResult(
            score=score,
            verdict=verdict,
            message=message,
            available=True,
        )

    # ──────────────────────────────────────────────────────────────────────────
    # Private helpers
    # ──────────────────────────────────────────────────────────────────────────

    def _classify(self, score: float) -> tuple[WatermarkVerdict, str]:
        """Map a raw detector score to a (verdict, message) pair."""
        if score >= self._DETECTED_THRESHOLD:
            return (
                "detected",
                (
                    f"Watermark detected (score: {score:.4f}). "
                    "This audio was likely generated by Chatterbox (Resemble AI)."
                ),
            )
        if score <= self._NOT_DETECTED_THRESHOLD:
            return (
                "not_detected",
                (
                    f"No watermark found (score: {score:.4f}). "
                    "This audio does not appear to be Chatterbox-generated."
                ),
            )
        return (
            "inconclusive",
            (
                f"Partial or degraded watermark signal detected (score: {score:.4f}). "
                "The result is ambiguous — the audio may have been post-processed."
            ),
        )
